### ISSUE TITLE
Variable redefinition

### ISSUE THREAD

**Issue by andersonfrailey** [andersonfrailey/StatMatch#11]
@XueliangWang, can you take a look at your import statements in `phase1.py`? You import two modules as `sm`. You'll need to either change the name of one of them or delete the module that isn't used.

**Comment by XueliangWang** [comment]
@andersonfrailey Oh... the second module is not used. I will delete it.

**Comment by andersonfrailey** [comment]
@XueliangWang can you submit the PR with just that change today. There are a couple other changes I want to make in the file
