### ISSUE TITLE
Matched file is not passing taxcalc requirements

### ISSUE THREAD

**Issue by hdoupe** [andersonfrailey/StatMatch#19]
I'm trying to feed the cps-matched-puf.csv file into a Records object, but it is failing some of the tests.

First, the cases of the variables in the python matched file did not match the cases expected by taxcalc.  I fixed this and will open a pull request with my solution.

Second, e00200 is not close enough to e00200s + e00200p in

`        if not np.allclose(self.e00200, (self.e00200p + self.e00200s),
                           rtol=0.0, atol=tol):
            raise ValueError(msg.format('e00200'))`

I'm working on this part now. 

@andersonfrailey

**Comment by andersonfrailey** [comment]
@hdoupe,`cps-matched-puf.csv` won't work with Tax-Calc until it has got through all of the steps in the tax-data repo. There are a couple issues with variable names I'm working on fixing in this repo that need to be implemented before running tax-data. I'll let you know when those are ready.

**Comment by hdoupe** [comment]
@andersonfrailey Ok, I see. Thanks
